### ISSUE TITLE
Cannot build demo quickstart because of error related to buildkit

### ISSUE THREAD

**Issue by bbird81** [sebo-b/warp#10]
Hi,
I'm unable to docker-compose the demo, I get the following error:
`ERROR: Service 'warp-demo-wsgi' failed to build: the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled`
I'm using a Ubuntu 20.04.

Tried to set env DOCKER_BUILDKIT=1 but I must be missing something.

Any advice? Thank you.

**Comment by sebo-b** [comment]
I think that you basically don't have buildkit installed. Please just update your docker version, here I found an instruction for you: https://docs.docker.com/engine/install/ubuntu/

Let me know if it still fails after that.

**Comment by bbird81** [comment]
That was it! Thank you very much :)

BTW there's a little typo in your read me in the section "without docker - the old way"; you probably meant "flask run" and not "flash run", just guessing! :)

Thanks again!

**Comment by sebo-b** [comment]
You're right - it should be `flask`, I'm constantly doing this typo in my terminal too...

Thanks, and I hope you will find this software usefull.
