### ISSUE TITLE
User: Admin Role -> Seat assign problem 

### ISSUE THREAD

**Issue by jpboehm** [sebo-b/warp#14]
Hi, thank you for WARP it is a great tool. 
However, I wanted to ask if only I have the following problem locally or if you can also prove it. 
If additional users with an admin role are created with the main or example admin (for teamleaders, for example), they cannot assign seats, only book them themselves. The example admin himself can also assign seats. Is that how it should work?

Thank you for your work and your answers :-). 
Best regards from Hamburg 
J.

**Comment by sebo-b** [comment]
Hi,

Zone admin should be able to assign seats. I have just checked it, and it works for me. Can you please put more details here, best with screenshots?

Cheers,
/S

**Comment by RespawnDespair** [comment]
Hi @jpboehm, is it possible that you have created a new zone? When adding users to this new zone, after creating them you have to switch their role from  'User' to 'Admin' from the overview table. This had me looking for a moment as well.

**Comment by jpboehm** [comment]
Hey @RespawnDespair, actually you are right. Thanks for the hint!
