### ISSUE TITLE
Docker install failed

### ISSUE THREAD

**Issue by cabe56** [sebo-b/warp#17]
After following the docker setup instructions in the [readme](https://github.com/sebo-b/warp#docker-compose), an error showed up:

> python setup.py bdist_wheel -d wheel:
> /usr/local/lib/python3.11/site-packages/setuptools/dist.py:548: UserWarning: The version specified ('2.0-rolling') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.

To finish installing, change the version param in `setup.py` from `2.0-rolling` to `2.0`.

I'm using MacOSX Ventura 13.1; Docker 4.16.2.

**Comment by sebo-b** [comment]
Thanks for the report. I pushed changes, it is fixed now.
