### ISSUE TITLE
Wokrspaces for a month

### ISSUE THREAD

**Issue by DzeTro** [sebo-b/warp#24]
First I would like to thank you after a bit of back and forth I managed to get Warp running.

Is there the possibility in the zone also like selection of the date to extend to a month so that you can see directly the whole month and book workplaces

**Comment by sebo-b** [comment]
Yes - you can configure how many weeks in advance (after the current week) are shown.

Either edit `config.py` or set `WARP_WEEKS_IN_ADVANCE` env variable.
