### ISSUE TITLE
LDAP configuration

### ISSUE THREAD

**Issue by Gjacquenot** [sebo-b/warp#26]
👋 

I would like to setup the LDAP authentification.

I usually have a `bind_cn` and a password fields to provide but I don't know where to set it in warp configuration.

The `bind_cn` field looks generally like that: `(bind_dn: 'CN=my_Ldap,OU=my_ou,DC=my_domain,DC=com') `

Any help would highly be appreciated!

Guillaume

**Comment by sebo-b** [comment]
Hi,

set up these environment variables as a bare minimum to make LDAP work:
```
WARP_AUTH_LDAP = "True"
WARP_LDAP_SERVER_URL = "ldap://your_ldap.example.org:389"
WARP_LDAP_USER_TEMPLATE = "CN={login},OU=my_ou,DC=my_domain,DC=com"
WARP_LDAP_STARTTLS = "True"
```
