### ISSUE TITLE
error while loading shared libraries: libpcre.so.3

### ISSUE THREAD

**Issue by sgutermann** [sebo-b/warp#30]
I just checked through the closed issues as well and the ReadMe one more time. However if I get it right, in order to testdrive I would just need to clone the repo and spin up the demo_compose.

Used a fresh debian VM. Got error.

```
warp-warp-demo-wsgi-1   | uwsgi: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory
```

What am I missing?

**Comment by 87113** [comment]
I don't know why, but my collegue had the same trouble and he did that : 

`docker compose -f demo_compose.yaml up --force-recreate --build -d warp-demo-wsgi`

**Comment by sgutermann** [comment]
Did not work for me. There seems to be a change in the Dockerfile at the beginning of the year, which I do not understand why it was made. However building it on a naked machine does not work anymore. 

Quick fix from a collegue, simply install libpcre3 again on the running image not only the build image.

So if you were running an building this thing bevor 2023 you DO NOT have any problems. If you are getting started fresh in 2023 you most likely will have this problem.

**Comment by 87113** [comment]
For informations:
* I build warp two weeks ago on linux (ubuntu) and I didn't have a problem
* my collegue tried on his windows11 machine and got this problem. 

If that could help!

**Comment by sgutermann** [comment]
I can not check that as I am running Ubuntu on the Laptop and in the VM I used for testing is Debian. I added on a fresh VM the above mentioned lines in the Dockerfile after line 41. I would rather have a few MB more and working than not :)

**Comment by sebo-b** [comment]
I assume that it is not a problem anymore and can be closed. Let me know if it is not.
