### ISSUE TITLE
Docker - demo issue

### ISSUE THREAD

**Issue by Hojoong-Kim92** [sebo-b/warp#32]
Hi. I was trying to start demo with docker but I got the below error.

uwsgi: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory

**Comment by sebo-b** [comment]
please check comments in this issue #30

**Comment by Hojoong-Kim92** [comment]
I didn't know this question already existed. After commenting out, it works normally.
Thank you!

**Comment by sebo-b** [comment]
you are welcome

can you please specify what setup (OS, docker version, etc) do you have, I would like to figure out why this issue exists.

**Comment by Hojoong-Kim92** [comment]
OS : Window11(22H2)
Docker Version : 24.0.2, build cb74dfc
