### ISSUE TITLE
error while loading shared libraries: libpcre.so.3

### ISSUE THREAD

**Issue by christianh17** [sebo-b/warp#33]
Sorry, but the error persists. I just tried to get it working but got the same error.
I used a fresh debian inside proxmox. The hints from the closed issue regarding the same problem did not help.
Do you have an idea what to do?
Kind regards
Tueftler

**Comment by MerlinsSake** [comment]
I had the same problem
 I solved this by editing the Dockerfile as follows

After the following lines:
FROM python:3-slim
WORKDIR /opt/warp

I added the lines:

RUN apt-get update
RUN apt-get install -y build-essential libpq-dev libpcre3 libpcre3-dev

In the second env, where the first is copied, this librarys are missing

**Comment by donbalon4** [comment]
@MerlinsSake thank you, your solution worked for me too!

**Comment by Hiten1928** [comment]
@MerlinsSake Do you know if there is anything that fixed the issue, I am still facing it on MacOS. Here is the stack trace on startup:
```
warp-warp-demo-db-1     | creating configuration files ... ok
warp-warp-demo-wsgi-1   | uwsgi: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory
warp-warp-demo-db-1     | running bootstrap script ... ok
```
