### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by jpboehm** [sebo-b/warp#9]
Hi, whenever I have set, like the doku says, the language in the WARP_LANGUAGE_FILE and restarted the app with a "custom" language (german in this case), all entries and links disappear. Unfortunately, the app does not load the additional i18n file. Do you have an idea what could be causing this?

**Comment by sebo-b** [comment]
Hi, can you please upload your german translation file? It's hard to say what's wrong without it.

**Comment by jpboehm** [comment]
Hi, yes this could be helpful ;-) 
https://github.com/jpboehm/warp/blob/6eebe99fd2be206d37428d4b14aa74f3cfa157ef/warp/static/i18n/de.js

**Comment by sebo-b** [comment]
Hi,

so it seems that the file is correct, which means that it is not accessible by the app. How do you run the app, in a container? If so, had you added this file to static folder before you built the docker image?

<img width="692" alt="image" src="https://user-images.githubusercontent.com/51707418/182130924-d3001903-98de-4e93-bb35-3c7fc53b944b.png">

**Comment by jpboehm** [comment]
Hi, I'm a newbie to docker unfortunately (any tips?). But I have started the app in a container. 
About the file: I put the de.js in the Static folder (next to the English and Polish variants), adjusted the demo_compose.yaml and fired it up (in one variant also the config.py) and it doesn't work. The app actually does not find the de.js. Have I forgotten essential steps? I am curious how and if it works in "porduction", if I get there. 

Thank you already for the quick answer and support.

**Comment by sebo-b** [comment]
ok, so please do the following steps:
- (just to be sure) check out the project again (git clone ...)
- copy your `de.js` to `warp/static/i18n directory`
- add `WARP_LANGUAGE_FILE: 'i18n/en.js'` to `environment` section in `demo_compose.yaml`
- rebuild containers without cache: `docker compose -f demo_compose.yaml build --no-cache`
- run container: `docker compose -f demo_compose.yaml up`

**Comment by sebo-b** [comment]
the problem you had is that docker used cached versions of containers where your de.js file was not present

**Comment by sebo-b** [comment]
you are welcome - enjoy!

**Comment by sebo-b** [comment]
ahh.. and feel free to make a pull request with your DE translation (when you think it is completed)
